version: '3'
services:
  app:
    image: node-products-gen
    build:
      context: .
    ports:
      - "3010:3010"
    command: npm run dev
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
